### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by capella-ben** [whitecatboard/blockly-environment#2]
Hi,

Can we please have more detailed instructions on how to compile the IDE for Windows?  

After a lot of mucking around I have complied a version (using a debian VM), but it can't connect to the board, so I must be missing something somewhere.  

The Lua-RTOS looks really good, would love to be able to use it.

**Comment by thunderWhitecat** [comment]
Hi @capella-ben,

The Whitecat IDE is now available on the web in alpha version. Please, use this version, you don't need to build. For windows you need:

* Download this: https://whitecatboard.org/downloads/windows.zip
* Uncompress an install
* Go to the installation folder an run the exe file
* This is The Whitecat Create Agent, a small piece of software that allows the communication between the IDE and your board using a serial connection

* Open a session in Google Chrome
* Go to https://ide.whitecatboard.org
* Sign in using your Google's Account

Yo have 2 programming models: blocks or lua. If you are in blocks you can switch to Lua pressing the ";" button in the toolbar. If you want switch to blocks press the "puzzle" button in the toolbar.

In the next weeks we have plans for document all and create the wiki!

Best regards,

Jaume

**Comment by capella-ben** [comment]
Thanks.

Can you please confirm the download URL for the agent.  I get 'Page not found'.

**Comment by thunderWhitecat** [comment]
Please, try again with the previous url.

https://whitecatboard.org/downloads/windows.zip
