### ISSUE TITLE
How to save LUA files

### ISSUE THREAD

**Issue by capella-ben** [whitecatboard/blockly-environment#3]
How does the IDE save files to the Lua-RTOS firmware?

Can this be done through a generic serial console?

**Comment by thunderWhitecat** [comment]
Hi @capella-ben,

The Whitecat IDE is now available on the web in alpha version. For windows you need:

* Download this: https://whitecatboard.org/downloads/windows.zip
* Uncompress an install
* Go to the installation folder an run the exe file
* This is The Whitecat Create Agent, a small piece of software that allows the communication between the IDE and your board using a serial connection

* Open a session in Google Chrome
* Go to https://ide.whitecatboard.org
* Sign in using your Google's Account

Yo have 2 programming models: blocks or lua. If you are in blocks you can switch to Lua pressing the ";" button in the toolbar. If you want switch to blocks press the "puzzle" button in the toolbar.

In the next weeks we have plans for document all and create the wiki!

Best regards,

Jaume
