### ISSUE TITLE
tooltips for switch to blocks/switch to Lua IDE button

### ISSUE THREAD

**Issue by ESP-EOS** [whitecatboard/blockly-environment#4]
It seems that the two tooltips are inverted. When I'm using Blocks editor, the button shows a semicolon (correct), but the tip is "switch to blocks" instead of "switch to Lua". Viceversa happens when I'm using Lua editor.

**Comment by thunderWhitecat** [comment]
Thanks for report this.

This is solved in https://github.com/whitecatboard/whitecat-ide/commit/94191091db25394ff620da9c520d548ef60e083b.

Changes will be uploaded into ide.whitecatboard.org in a few days.
