### ISSUE TITLE
input/output 

### ISSUE THREAD

**Issue by aresrepair** [whitecatboard/blockly-environment#9]
hello!

input/output block not working

**Comment by thunderWhitecat** [comment]
Hi @aresrepair,

Which type of error you give?

**Comment by thunderWhitecat** [comment]
@aresrepair,

Please, try again. I have found some related issues about input/output with last IDE update.

**Comment by aresrepair** [comment]
Hi jolivepetrus,
Can't move input/output block to work place
![image](https://user-images.githubusercontent.com/4078184/33240488-8bb5ef00-d2c7-11e7-9f94-cfb23f9fb2d3.png)
if I do double click on IO block 
it disappear
if I click to other and return to IO block
I have this:
![image](https://user-images.githubusercontent.com/4078184/33240508-d62cc298-d2c7-11e7-87c5-63162940d490.png)
but this block not moving too

thank you for replay

**Comment by thunderWhitecat** [comment]
This is a know bug, that I will try to resolve tonight.
Please, attach a board with a Lua RTOS firmware, and it will work.

**Comment by thunderWhitecat** [comment]
Please, try again, it should work now.
